spring:
  application:
    name: web-opensource-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_software
    username: root
    password: 1q2w3e4r!
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
